controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 0.5 #0.5
  min_vel_x: 0.1 #0.01
  max_vel_theta: 1.5 #1.5

  min_in_place_vel_theta: 0.314

  acc_lim_theta: 2.14
  acc_lim_x: 1.8
  acc_lim_y: 1.8

  sim_time: 2.0
  # sim_granularity: 0.1

  vx_samples: 10.0
  vtheta_samples: 20.0

  pdist_scale: 2.2 #0.6
  gdist_scale: 0.4 #0.8
  occdist_scale: 0.1
  heading_lookahead: 1
  holonomic_robot: false
  meter_scoring: true 
  # dwa: true
  publish_cost_grid: true