map_type: costmap

# obstacle_range: 2.0 # 2.0
# raytrace_range: 3.0 # 3.0

transform_tolerance: 0.2 # 0.0

# robot_radius: 0.3 # 0.0

# inflation_radius: 0.3 # 0.0

# max_obstacle_height: 10
# min_obstacle_height: -10



# observation_sources: laser_scan_sensor
# laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: scan, marking: true, clearing: true, max_obstacle_height: 10,
# min_obstacle_height: -10}
