global_costmap:
   global_frame: /map
   
   robot_base_frame: robot_footprint
   update_frequency: 2.0
   publish_frequency: 2.0
   width: 30.0
   height: 30.0
   resolution: 0.025
   static_map: true
   rolling_window: false

   
    
   inflater_layer:
    obstacle_range: 2.0 # 2.0
    raytrace_range: 3.0 # 3.0
    robot_radius: 0.12 # 0.0
    inflation_radius: 0.2
    cost_scaling_factor: 10.5
   #  cost_factor: 0.55
   #  neutral_cost: 66


   plugins:
      
      - {name: static_layer, type: "costmap_2d::StaticLayer"}
      - {name: inflater_layer, type: "costmap_2d::InflationLayer"}


   
   
   
   
   
   
   