local_costmap:
  global_frame: odom
  robot_base_frame: robot_footprint
  update_frequency: 5.0
  publish_frequency: 5.0
  width: 4.0
  height: 4.0
  resolution: 0.025
  static_map: false
  rolling_window: true
  meter_scoring: true 

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: scan, marking: true, clearing: true, max_obstacle_height: 10,
    min_obstacle_height: -10, inf_is_valid: true, obstacle_range: 2, combination_method: 0, raytrace_range: 3}
    
  inflater_layer:

    obstacle_range: 2.0 # 2.0
    raytrace_range: 3 # 3.0
    robot_radius: 0.12 # 0.0
    inflation_radius: 0.2 #0.555
    cost_scaling_factor: 8.5 #10.0
    
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflater_layer, type: "costmap_2d::InflationLayer"}
